/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joesicecream.view;

/**
 *
 * @author Shaka
 */
public class IceCreamJForm extends javax.swing.JFrame {

    public float subtotal;
    public float total;
    public final float IVA = 0.16f;
    public float ivaCalculado;
    /**
     * Creates new form IceCreamJForm
     */
    public IceCreamJForm() {
        initComponents();
        buttonGroup1.add(chocolateRadio);
        buttonGroup1.add(vainillaRadio);
        buttonGroup1.add(fresaRadio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chocolateCheck = new java.awt.Checkbox();
        jLabel5 = new javax.swing.JLabel();
        chispasChocCheck = new java.awt.Checkbox();
        jLabel6 = new javax.swing.JLabel();
        chispasSaboresCheck = new java.awt.Checkbox();
        jLabel7 = new javax.swing.JLabel();
        jaleaCheck = new java.awt.Checkbox();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chocolateRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        vainillaRadio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        fresaRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        calcularBoton = new javax.swing.JButton();
        limpiarBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        subtotalText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ivaText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 1, 48)); // NOI18N
        jLabel1.setText("La Michoacana");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        chocolateCheck.setLabel("Chocolate líquido");
        jPanel2.add(chocolateCheck);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("$3.00");
        jPanel2.add(jLabel5);

        chispasChocCheck.setLabel("Chispas de chocolate");
        jPanel2.add(chispasChocCheck);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$5.00");
        jPanel2.add(jLabel6);

        chispasSaboresCheck.setLabel("Chispas de sabores");
        jPanel2.add(chispasSaboresCheck);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("$3.00");
        jPanel2.add(jLabel7);

        jaleaCheck.setLabel("Jalea");
        jPanel2.add(jaleaCheck);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("$7.00");
        jPanel2.add(jLabel8);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        chocolateRadio.setText("Chocolate");
        jPanel3.add(chocolateRadio);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("$10.00");
        jPanel3.add(jLabel2);

        vainillaRadio.setText("Vainilla");
        jPanel3.add(vainillaRadio);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("$15.00");
        jPanel3.add(jLabel3);

        fresaRadio.setText("Fresa");
        jPanel3.add(fresaRadio);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("$12.00");
        jPanel3.add(jLabel4);

        calcularBoton.setText("Calcular");
        calcularBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBotonActionPerformed(evt);
            }
        });

        limpiarBoton.setText("Limpiar Forma");
        limpiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel9.setText("Subtotal");
        jPanel1.add(jLabel9);

        subtotalText.setEditable(false);
        subtotalText.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(subtotalText);

        jLabel10.setText("IVA");
        jPanel1.add(jLabel10);

        ivaText.setEditable(false);
        ivaText.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ivaText);

        jLabel11.setText("Total");
        jPanel1.add(jLabel11);

        totalText.setEditable(false);
        totalText.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(totalText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(calcularBoton)
                                .addGap(18, 18, 18)
                                .addComponent(limpiarBoton)
                                .addGap(18, 18, 18)
                                .addComponent(salirBoton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calcularBoton)
                            .addComponent(limpiarBoton)
                            .addComponent(salirBoton))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(56, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBotonActionPerformed
        // TODO add your handling code here:
        if(chocolateRadio.isSelected())
            subtotal = subtotal + 10;
        else if(vainillaRadio.isSelected())
            subtotal = subtotal + 15;
        else if(fresaRadio.isSelected())
            subtotal = subtotal + 12;
        
        if(chocolateCheck.getState())
            subtotal = subtotal + 3;
        
        if(chispasChocCheck.getState())
            subtotal = subtotal + 5;
        
        if(chispasSaboresCheck.getState())
            subtotal = subtotal + 3;
        
        if(jaleaCheck.getState())
            subtotal = subtotal + 7;
        
        subtotalText.setText(subtotal+"");
        
        ivaCalculado = subtotal*IVA;
        ivaText.setText(ivaCalculado+"");
        
        total = subtotal + ivaCalculado;
        totalText.setText(total+"");
        
        
    }//GEN-LAST:event_calcularBotonActionPerformed

    private void limpiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBotonActionPerformed
        // TODO add your handling code here:
        /*chocolateRadio.setSelected(false);
        vainillaRadio.setSelected(false);
        fresaRadio.setSelected(false);*/
        buttonGroup1.clearSelection();
        
        chocolateCheck.setState(false);
        chispasChocCheck.setState(false);
        chispasSaboresCheck.setState(false);
        jaleaCheck.setState(false);
        
        subtotalText.setText("");
        ivaText.setText("");
        totalText.setText("");
        
        total = 0f;
        ivaCalculado = 0f;
        subtotal = 0f;
    }//GEN-LAST:event_limpiarBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IceCreamJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IceCreamJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IceCreamJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IceCreamJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IceCreamJForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcularBoton;
    private java.awt.Checkbox chispasChocCheck;
    private java.awt.Checkbox chispasSaboresCheck;
    private java.awt.Checkbox chocolateCheck;
    private javax.swing.JRadioButton chocolateRadio;
    private javax.swing.JRadioButton fresaRadio;
    private javax.swing.JTextField ivaText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Checkbox jaleaCheck;
    private javax.swing.JButton limpiarBoton;
    private javax.swing.JButton salirBoton;
    private javax.swing.JTextField subtotalText;
    private javax.swing.JTextField totalText;
    private javax.swing.JRadioButton vainillaRadio;
    // End of variables declaration//GEN-END:variables
}
